In [13]:
%load_ext autoreload
%autoreload 2

import os
import pandas as pd
import numpy as np

In [17]:
import my_utils

my_utils.add_2_numbers(4, 2)

6

In [18]:
from my_utils import add_2_numbers

add_2_numbers(2, 3)

5

In [19]:
import my_utils as myu

myu.add_2_numbers(2,2)

4

In [22]:
from my_utils import *

df = pd.read_csv('../data/ETFs/spy.us.txt')
get_technical_indicators(df, 'Close')

,Date,Open,High,Low,Close,Volume,OpenInt,ma7,ma21,26ema,12ema,MACD,20sd,upper_band,lower_band,ema,momentum,log_momentum
0,2005-02-25,104.77,106.000,104.680,105.79,70221808,0,NaN,NaN,105.790000,105.790000,0.000000,NaN,NaN,NaN,105.790000,104.79,4.651958
1,2005-02-28,105.55,105.680,104.560,105.08,79695344,0,NaN,NaN,105.421346,105.405417,-0.015929,NaN,NaN,NaN,105.257500,104.08,4.645160
2,2005-03-01,105.22,105.870,105.220,105.62,54607412,0,NaN,NaN,105.492721,105.489169,-0.003552,NaN,NaN,NaN,105.508462,104.62,4.650335
3,2005-03-02,105.21,106.220,105.100,105.57,73733090,0,NaN,NaN,105.514325,105.514684,0.000359,NaN,NaN,NaN,105.550000,104.57,4.649857
4,2005-03-03,105.99,106.200,105.150,105.61,71286823,0,NaN,NaN,105.536512,105.540581,0.004069,NaN,NaN,NaN,105.590165,104.61,4.650239
5,2005-03-04,106.31,107.010,106.100,106.93,64483624,0,NaN,NaN,105.815617,105.878283,0.062666,NaN,NaN,NaN,106.484615,105.93,4.662778
6,2005-03-07,106.86,107.380,106.620,106.97,50288014,0,105.938571,NaN,106.020918,106.121896,0.100978,NaN,NaN,NaN,106.808353,105.97,4.663156
7,2005-03-08,106.87,107.150,106.360,106.55,51274973,0,106.047143,NaN,106.106166,106.211234,0.105069,NaN,NaN,NaN,106.636091,105.55,4.659185
8,2005-03-09,106.25,106.520,105.380,105.39,84491113,0,106.091429,NaN,106.000014,106.048765,0.048751,NaN,NaN,NaN,105.805322,104.39,4.648134
9,2005-03-10,105.40,105.850,104.890,105.62,74962248,0,106.091429,NaN,105.947576,105.967514,0.019938,NaN,NaN,NaN,105.681772,104.62,4.650335
10,2005-03-11,105.88,106.040,104.660,104.88,66729930,0,105.992857,NaN,105.809111,105.768525,-0.040586,NaN,NaN,NaN,105.147254,103.88,4.643236
11,2005-03-14,104.89,105.560,104.780,105.54,41713280,0,105.982857,NaN,105.776047,105.727894,-0.048152,NaN,NaN,NaN,105.409085,104.54,4.649570
12,2005-03-15,105.78,105.820,104.600,104.65,71730138,0,105.657143,NaN,105.644130,105.540731,-0.103400,NaN,NaN,NaN,104.903028,103.65,4.641020
13,2005-03-16,104.27,104.440,103.590,103.77,88074366,0,105.200000,NaN,105.433643,105.239232,-0.194411,NaN,NaN,NaN,104.147676,102.77,4.632493
14,2005-03-17,103.94,104.310,103.650,103.99,72019178,0,104.834286,NaN,105.277476,105.029964,-0.247512,NaN,NaN,NaN,104.042559,102.99,4.634632
15,2005-03-18,103.75,104.130,102.930,103.26,71037158,0,104.530000,NaN,105.066432,104.737464,-0.328968,NaN,NaN,NaN,103.520853,102.26,4.627519
16,2005-03-21,103.42,103.480,102.590,102.89,70515555,0,104.140000,NaN,104.845505,104.435601,-0.409904,NaN,NaN,NaN,103.100284,101.89,4.623894
17,2005-03-22,103.11,103.600,101.850,101.85,107137486,0,103.707143,NaN,104.549554,104.017126,-0.532428,NaN,NaN,NaN,102.266761,100.85,4.613634
18,2005-03-23,101.87,102.560,101.710,101.93,82588253,0,103.191429,NaN,104.296991,103.682010,-0.614981,NaN,NaN,NaN,102.042254,100.93,4.614427
19,2005-03-24,102.33,102.790,101.980,102.05,59713798,0,102.820000,NaN,104.085083,103.421718,-0.663365,1.604461,NaN,NaN,102.047418,101.05,4.615615
20,2005-03-28,102.29,102.750,102.190,102.19,53885043,0,102.594286,104.577619,103.909907,103.226372,-0.683535,1.675741,107.929100,101.226138,102.142473,101.19,4.617000
21,2005-03-29,102.05,102.710,101.270,101.51,83849903,0,102.240000,104.373810,103.692066,102.955448,-0.736618,1.798272,107.970353,100.777266,101.720824,100.51,4.610257
22,2005-03-30,101.85,102.980,101.720,102.96,72199510,0,102.197143,104.272857,103.626707,102.956164,-0.670544,1.796870,107.866597,100.679117,102.546941,101.96,4.624581
23,2005-03-31,102.97,103.190,102.680,102.77,74669192,0,102.180000,104.137143,103.551366,102.926994,-0.624373,1.794038,107.725219,100.549066,102.695647,101.77,4.622715
24,2005-04-01,103.34,103.660,101.850,102.30,111800673,0,102.244286,103.981429,103.442823,102.829029,-0.613794,1.796731,107.574890,100.387967,102.431882,101.30,4.618086
25,2005-04-04,102.24,102.670,101.700,102.48,82200501,0,102.322857,103.832381,103.360353,102.774625,-0.585728,1.673037,107.178454,100.486308,102.463961,101.48,4.619862
26,2005-04-05,102.60,103.120,102.520,102.97,57487581,0,102.454286,103.643810,103.327300,102.805017,-0.522283,1.487527,106.618863,100.668756,102.801320,101.97,4.624679
27,2005-04-06,103.19,103.620,102.960,103.32,61195953,0,102.615714,103.470000,103.326689,102.884989,-0.441699,1.299896,106.069793,100.870207,103.147107,102.32,4.628105
28,2005-04-07,103.15,103.890,103.060,103.87,54209783,0,102.952857,103.342381,103.371773,103.037732,-0.334041,1.213841,105.770063,100.914698,103.629036,102.87,4.633466
29,2005-04-08,103.81,103.850,102.800,102.80,73804604,0,102.930000,103.219048,103.324746,103.000912,-0.323833,1.079141,105.377331,101.060765,103.076345,101.80,4.623010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3171,2017-10-02,251.49,252.320,251.293,252.32,58814862,0,250.200000,248.691429,248.366943,249.896023,1.529080,1.982329,252.656086,244.726772,251.835952,251.32,5.526727
3172,2017-10-03,252.46,252.890,252.230,252.86,66633788,0,250.688571,248.988571,248.699762,250.352020,1.652258,1.952274,252.893119,245.084024,252.518651,251.86,5.528873
3173,2017-10-04,252.69,253.440,252.560,253.16,55799301,0,251.292857,249.384286,249.030150,250.784017,1.753867,1.960864,253.306014,245.462557,252.946217,252.16,5.530064
3174,2017-10-05,253.54,254.680,253.400,254.66,63351836,0,252.090000,249.811429,249.447176,251.380322,1.933146,2.047370,253.906169,245.716688,254.088739,253.66,5.535995
3175,2017-10-06,254.15,254.460,253.850,254.37,80583147,0,252.707143,250.226190,249.811829,251.840272,2.028443,1.958931,254.144052,246.308329,254.276246,253.37,5.534851
3176,2017-10-09,254.20,254.420,253.650,253.95,35700286,0,253.221429,250.634762,250.118361,252.164846,2.046485,2.013781,254.662324,246.607200,254.058749,252.95,5.533192
3177,2017-10-10,254.60,255.050,253.980,254.62,42854696,0,253.705714,250.950952,250.451815,252.542562,2.090746,2.132678,255.216308,246.685597,254.432916,253.62,5.535837
3178,2017-10-11,254.51,255.020,254.320,255.02,47525531,0,254.091429,251.246190,250.790199,252.923706,2.133507,2.245314,255.736818,246.755563,254.824305,254.02,5.537413
3179,2017-10-12,254.66,255.060,254.365,254.64,46830626,0,254.345714,251.517619,251.075370,253.187751,2.112381,2.278133,256.073885,246.961353,254.701435,253.64,5.535916
3180,2017-10-13,255.14,255.179,254.640,254.95,54633114,0,254.601429,251.807619,251.362379,253.458866,2.096487,2.314504,256.436627,247.178611,254.867145,253.95,5.537137
3181,2017-10-16,255.21,255.510,254.820,255.29,38098302,0,254.691429,252.098095,251.653314,253.740579,2.087265,2.368002,256.834099,247.362092,255.149048,254.29,5.538475
3182,2017-10-17,255.23,255.520,254.980,255.47,31458749,0,254.848571,252.371905,251.936032,254.006644,2.070612,2.412268,257.196441,247.547368,255.363016,254.47,5.539183
3183,2017-10-18,255.90,255.950,255.500,255.72,40619940,0,255.101429,252.645714,252.216326,254.270237,2.053912,2.443739,257.533191,247.758237,255.601005,254.72,5.540165
3184,2017-10-19,254.83,255.830,254.350,255.79,61697632,0,255.268571,252.918571,252.481042,254.504047,2.023005,2.395712,257.709996,248.127147,255.727002,254.79,5.540440
3185,2017-10-20,256.70,257.140,256.420,257.11,89076124,0,255.567143,253.286190,252.823928,254.904963,2.081035,2.393731,258.073653,248.498728,256.649001,256.11,5.545607
3186,2017-10-23,257.48,257.510,256.020,256.11,63839591,0,255.777143,253.603810,253.067341,255.090353,2.023012,2.206776,258.017362,249.190257,256.289667,255.11,5.541695
3187,2017-10-24,256.59,256.830,256.150,256.56,65036277,0,256.007143,253.967143,253.326056,255.316453,1.990396,1.980272,257.927687,250.006599,256.469889,255.56,5.543457
3188,2017-10-25,256.18,256.310,254.000,255.29,103490465,0,256.007143,254.262857,253.471534,255.312383,1.840849,1.731751,257.726359,250.799356,255.683296,254.29,5.538475
3189,2017-10-26,255.99,256.300,255.480,255.62,69644570,0,256.028571,254.528095,253.630679,255.359709,1.729029,1.449189,257.426473,251.629717,255.641099,254.62,5.539772
3190,2017-10-27,256.47,257.890,256.160,257.71,85253763,0,256.312857,254.878571,253.932851,255.721292,1.788441,1.344442,257.567456,252.189687,257.020366,256.71,5.547947
3191,2017-10-30,257.07,257.600,256.410,256.75,54260547,0,256.450000,255.141429,254.141529,255.879555,1.738026,1.229064,257.599557,252.683300,256.840122,255.75,5.544200
3192,2017-10-31,257.18,257.440,256.805,257.15,59437242,0,256.455714,255.371429,254.364379,256.075008,1.710629,1.156224,257.683876,253.058981,257.046707,256.15,5.545763
3193,2017-11-01,258.04,258.430,257.070,257.49,54173392,0,256.652857,255.591905,254.595906,256.292699,1.696793,1.099599,257.791103,253.392706,257.342236,256.49,5.547090
3194,2017-11-02,257.41,257.750,256.190,257.59,56424826,0,256.800000,255.802857,254.817691,256.492284,1.674593,1.146055,258.094967,253.510747,257.507412,256.59,5.547479
3195,2017-11-03,257.77,258.500,257.300,258.45,59578151,0,257.251429,255.983333,255.086751,256.793471,1.706720,1.227129,258.437592,253.529075,258.135804,257.45,5.550826
3196,2017-11-06,258.30,259.000,258.220,258.85,49529148,0,257.712857,256.196667,255.365510,257.109860,1.744350,1.271207,258.739081,253.654253,258.611935,257.85,5.552378
3197,2017-11-07,258.97,259.350,258.110,258.67,57218448,0,257.850000,256.421429,255.610287,257.349881,1.739594,1.309979,259.041387,253.801471,258.650645,257.67,5.551680
3198,2017-11-08,258.47,259.220,258.150,259.11,50277699,0,258.187143,256.635238,255.869525,257.620669,1.751144,1.382143,259.399525,253.870952,258.956882,258.11,5.553386
3199,2017-11-09,257.73,258.390,256.360,258.17,94537282,0,258.332857,256.785238,256.039931,257.705181,1.665251,1.327391,259.440020,254.130456,258.432294,257.17,5.549737
3200,2017-11-10,257.73,258.210,257.370,258.09,59862364,0,258.418571,256.949524,256.191788,257.764384,1.572597,1.270000,259.489524,254.409524,258.204098,257.09,5.549426

Packages are modules in a folder with an init

In [18]:
from mypkg import my_utils

In [19]:
my_utils.divide_by_const(3)

0.3

In [20]:
my_utils.multiply_by_const(3)

30

Slicing datetime indexed dataframes

In [25]:
df.index = df.Date

In [26]:
df['2005-03-11': '2005-03-15']

,Date,Open,High,Low,Close,Volume,OpenInt,ma7,ma21,26ema,12ema,MACD,20sd,upper_band,lower_band,ema,momentum,log_momentum
Date,,,,,,,,,,,,,,,,,,
2005-03-11,2005-03-11,105.88,106.04,104.66,104.88,66729930,0,105.992857,NaN,105.809111,105.768525,-0.040586,NaN,NaN,NaN,105.147254,103.88,4.643236
2005-03-14,2005-03-14,104.89,105.56,104.78,105.54,41713280,0,105.982857,NaN,105.776047,105.727894,-0.048152,NaN,NaN,NaN,105.409085,104.54,4.649570
2005-03-15,2005-03-15,105.78,105.82,104.60,104.65,71730138,0,105.657143,NaN,105.644130,105.540731,-0.103400,NaN,NaN,NaN,104.903028,103.65,4.641020